### PR TITLE
Badges

### PR DESCRIPTION
**Pull request by michaelachrisco**

### CODE REVIEW

**Comment by michaelachrisco** [comment]
@josephbridgwaterrowe Please review.

**Comment by josephbridgwaterrowe** [comment]
Did you see that CodeClimate isn't very happy?

**Comment by michaelachrisco** [comment]
Yes. I brought up the GPA from 2.2 to 3.0. Was planning on taking another look when I get a chance.

**Comment by josephbridgwaterrowe** [comment]
Cool, merging.

**Pull request merged**
